{
 "title": "Gochat System Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic - Req/s",
   "type": "timeseries",
   "description": "Number of Requests",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(echo_requests_total{}[2m])) by (job)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(echo_requests_total{}[2m])) by (job, method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Number of Go Routines Count",
   "type": "gauge",
   "description": "Number of Go Routine currently running in the service",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"gochat:9080\"}"
    }
   ]
  },
  {
   "title": "Number of Os thread Created",
   "type": "gauge",
   "description": "The number of OS threads created aginst goroutines",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"gochat:9080\"}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Errors - % (4xx)",
   "type": "timeseries",
   "description": "Number of 4xx errors",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=\"api-server\", url=~\".+\", code=~\"4.+\"}[5m])) by (job) /\nsum(rate(echo_requests_total{job=\"api-server\", url=~\".+\"}[5m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (4xx)",
   "type": "timeseries",
   "description": "Number of 4xx errors by each URL",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=~\"api-server\", url=~\".+\", code=~\"4.+\"}[5m])) by (job, method, url, code)/sum(rate(echo_requests_total{job=~\"api-server\", url=~\".+\"}[5m])) by (job, method, url, code)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}} - {{code}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total 4xx Errors",
   "type": "gauge",
   "description": "A total number of 4xx errors occurred",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(rate(echo_requests_total{code=~\"4.+\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "description": "Number of 5xx errors",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=\"api-server\", url=~\".+\", code=~\"5.+\"}[5m])) by (job) /\nsum(rate(echo_requests_total{job=\"api-server\", url=~\".+\"}[5m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "timeseries",
   "description": "Number of 5xx errors by each URL",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(echo_requests_total{job=\"api-server\", url=~\".+\", code=~\"5.+\"}[5m])) by (job, method, url, code) /\nsum(rate(echo_requests_total{job=\"api-server\", url=~\".+\"}[5m])) by (job, method, url, code)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}} - {{code}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total 5xx Errors",
   "type": "gauge",
   "description": "A total number of 5xx errors occurred",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(rate(echo_requests_total{code=~\"5.+\"}[5m])) by (job)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Latency - General",
   "type": "timeseries",
   "description": "General latency",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "timeseries",
   "description": "Handler Latency",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, method, handler, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, method, url, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, method, url, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p99"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "timeseries",
   "description": "Instance Latency",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p50"
    },
    {
     "expr": "histogram_quantile(.95, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(echo_request_duration_seconds_bucket{job=~\"api-server\",instance=~\".+\", url=~\".+\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}